version: "3"
services:
  service-1:
    build: .
    ports:
      - "8080:8000"
    depends_on:
      - redis
  service-2:
    build: .
    ports:
      - "8081:8000"
    depends_on:
      - redis
  redis:
    image: redis
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8084:8001"