version: "3"
services:
  service-1:
    build: .
    ports:
      - "8080:8000"
    depends_on:
      - redis
    restart: always
  service-2:
    build: .
    ports:
      - "8081:8000"
    depends_on:
      - redis
    restart: always
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8084:8001"
    restart: always
